export interface Recipe {
  instructions: string;
  ingredients: Array<{ item: string; quantity: string }>;
  imageUrl?: string;
}

export const RECIPES: Record<string, Recipe> = {
  // ── Breakfasts ──────────────────────────────────────────────────────────────
  "Scrambled eggs (3) with whole grain toast": {
    instructions: "Whisk 3 eggs with a pinch of salt. Melt butter in a non-stick pan on medium heat, pour in eggs and stir slowly until just set. Serve on toasted whole grain bread.",
    ingredients: [
      { item: "Eggs", quantity: "3" },
      { item: "Butter", quantity: "1 tsp" },
      { item: "Whole grain bread", quantity: "2 slices" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Oatmeal with berries and almonds": {
    instructions: "Bring 200ml water or milk to a simmer. Stir in oats and cook 3-5 minutes until creamy. Top with fresh berries, sliced almonds, and a drizzle of honey.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Milk or water", quantity: "200ml" },
      { item: "Fresh berries", quantity: "100g" },
      { item: "Almonds, sliced", quantity: "25g" },
      { item: "Honey", quantity: "1 tsp (optional)" },
    ],
  },
  "Greek yogurt with granola and honey": {
    instructions: "Spoon Greek yogurt into a bowl. Top with granola and drizzle with honey. Add fresh fruit if desired.",
    ingredients: [
      { item: "Greek yogurt (full-fat)", quantity: "200g" },
      { item: "Granola", quantity: "45g" },
      { item: "Honey", quantity: "1 tbsp" },
      { item: "Fresh fruit", quantity: "80g (optional)" },
    ],
  },
  "Egg white omelette with spinach and feta": {
    instructions: "Whisk egg whites with a pinch of salt. Pour into a non-stick pan on medium heat. When the edges set, add spinach and feta to one half, fold and cook 1 more minute.",
    ingredients: [
      { item: "Egg whites", quantity: "5 (or 150ml carton)" },
      { item: "Baby spinach", quantity: "60g" },
      { item: "Feta cheese", quantity: "30g" },
      { item: "Olive oil spray", quantity: "1 spray" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Protein smoothie with oats and almond butter": {
    instructions: "Add all ingredients to a blender. Blend until smooth. Add more milk for a thinner consistency.",
    ingredients: [
      { item: "Protein powder (vanilla)", quantity: "1 scoop (30g)" },
      { item: "Rolled oats", quantity: "40g" },
      { item: "Almond butter", quantity: "1 tbsp" },
      { item: "Banana", quantity: "1/2" },
      { item: "Milk or almond milk", quantity: "250ml" },
    ],
  },
  "Cottage cheese with berries and flaxseed": {
    instructions: "Spoon cottage cheese into a bowl. Top with fresh berries and sprinkle with ground flaxseed.",
    ingredients: [
      { item: "Low-fat cottage cheese", quantity: "200g" },
      { item: "Mixed berries", quantity: "120g" },
      { item: "Ground flaxseed", quantity: "1 tbsp" },
      { item: "Honey", quantity: "1 tsp (optional)" },
    ],
  },
  "Smoked salmon with eggs and rye toast": {
    instructions: "Poach or scramble eggs. Serve on toasted rye bread with smoked salmon and a squeeze of lemon.",
    ingredients: [
      { item: "Smoked salmon", quantity: "80g" },
      { item: "Eggs", quantity: "2" },
      { item: "Rye bread", quantity: "2 slices" },
      { item: "Lemon", quantity: "1/4" },
      { item: "Capers (optional)", quantity: "1 tsp" },
    ],
  },
  "Chia seed pudding with coconut milk and nuts": {
    instructions: "Mix chia seeds with coconut milk. Refrigerate overnight or for at least 2 hours. Top with mixed nuts and fresh fruit before serving.",
    ingredients: [
      { item: "Chia seeds", quantity: "40g" },
      { item: "Coconut milk", quantity: "200ml" },
      { item: "Mixed nuts", quantity: "25g" },
      { item: "Fresh fruit", quantity: "80g" },
    ],
  },
  // ── Lunches ─────────────────────────────────────────────────────────────────
  "Grilled chicken breast with brown rice and broccoli": {
    instructions: "Season chicken with olive oil, garlic, salt and pepper. Grill 6-7 min each side. Cook rice per packet. Steam broccoli 4-5 min.",
    ingredients: [
      { item: "Chicken breast", quantity: "180g" },
      { item: "Brown rice", quantity: "60g (dry)" },
      { item: "Broccoli florets", quantity: "150g" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  "Turkey and avocado salad with olive oil dressing": {
    instructions: "Slice turkey and avocado. Arrange over mixed leaves with cucumber and tomato. Whisk olive oil, lemon juice, salt and pepper and drizzle over.",
    ingredients: [
      { item: "Turkey breast slices", quantity: "120g" },
      { item: "Avocado", quantity: "1/2" },
      { item: "Mixed salad leaves", quantity: "80g" },
      { item: "Cherry tomatoes", quantity: "80g" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
    ],
  },
  "Tuna salad with olive oil dressing": {
    instructions: "Drain tuna and flake into a bowl. Add cucumber, red onion, and cherry tomatoes. Dress with olive oil and lemon juice.",
    ingredients: [
      { item: "Canned tuna in water", quantity: "160g (drained)" },
      { item: "Mixed salad leaves", quantity: "80g" },
      { item: "Cucumber", quantity: "1/4" },
      { item: "Red onion", quantity: "1/4 small" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
    ],
  },
  "Quinoa bowl with chickpeas and vegetables": {
    instructions: "Cook quinoa per packet. Drain and rinse chickpeas. Combine with roasted peppers, cucumber, and parsley. Dress with lemon and olive oil.",
    ingredients: [
      { item: "Quinoa", quantity: "60g (dry)" },
      { item: "Chickpeas", quantity: "120g (cooked)" },
      { item: "Bell pepper", quantity: "1/2" },
      { item: "Cucumber", quantity: "1/2" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
    ],
  },
  "Salmon with sweet potato and asparagus": {
    instructions: "Bake salmon at 200°C for 12-15 min. Cube sweet potato and roast with olive oil at 200°C for 25 min. Roast asparagus last 10 min alongside.",
    ingredients: [
      { item: "Salmon fillet", quantity: "160g" },
      { item: "Sweet potato", quantity: "180g" },
      { item: "Asparagus", quantity: "120g" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Lemon", quantity: "1/2" },
    ],
  },
  "Beef and brown rice bowl with mixed vegetables": {
    instructions: "Season lean beef strips with soy sauce and garlic. Stir-fry 3-4 min. Cook brown rice. Steam or stir-fry mixed vegetables. Combine in a bowl.",
    ingredients: [
      { item: "Lean beef strips", quantity: "160g" },
      { item: "Brown rice", quantity: "60g (dry)" },
      { item: "Mixed stir-fry vegetables", quantity: "150g" },
      { item: "Soy sauce", quantity: "1 tbsp" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Sesame oil", quantity: "1 tsp" },
    ],
  },
  "Chicken Caesar salad with whole grain croutons": {
    instructions: "Grill chicken breast and slice. Toss romaine lettuce with Caesar dressing and parmesan. Add chicken and whole grain croutons on top.",
    ingredients: [
      { item: "Chicken breast", quantity: "160g" },
      { item: "Romaine lettuce", quantity: "120g" },
      { item: "Parmesan, grated", quantity: "20g" },
      { item: "Whole grain bread, cubed", quantity: "1 slice" },
      { item: "Caesar dressing", quantity: "2 tbsp" },
      { item: "Olive oil", quantity: "1 tsp" },
    ],
  },
  "Lean turkey mince bowl with quinoa and greens": {
    instructions: "Brown turkey mince with garlic and cumin. Cook quinoa. Wilt spinach in the pan. Serve mince over quinoa and greens.",
    ingredients: [
      { item: "Lean turkey mince", quantity: "160g" },
      { item: "Quinoa", quantity: "60g (dry)" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Ground cumin", quantity: "1 tsp" },
      { item: "Olive oil", quantity: "1 tbsp" },
    ],
  },
  // ── Dinners ─────────────────────────────────────────────────────────────────
  "Baked chicken with roasted vegetables and sweet potato": {
    instructions: "Season chicken with herbs, olive oil, salt and pepper. Bake at 200°C for 25-30 min. Cube sweet potato and vegetables, roast alongside last 25 min.",
    ingredients: [
      { item: "Chicken breast", quantity: "200g" },
      { item: "Sweet potato", quantity: "200g" },
      { item: "Mixed vegetables (courgette, pepper, onion)", quantity: "200g" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Mixed dried herbs", quantity: "1 tsp" },
    ],
  },
  "Lean beef with mashed potatoes and green beans": {
    instructions: "Grill or pan-fry lean beef steak to your liking. Boil potatoes, mash with a little butter and milk. Steam green beans 4-5 min.",
    ingredients: [
      { item: "Lean beef steak", quantity: "180g" },
      { item: "Potatoes", quantity: "240g" },
      { item: "Butter", quantity: "1 tsp" },
      { item: "Milk", quantity: "2 tbsp" },
      { item: "Green beans", quantity: "150g" },
    ],
  },
  "Grilled salmon with wild rice and vegetables": {
    instructions: "Season salmon and grill 4-5 min each side. Cook wild rice per packet. Steam or stir-fry vegetables with a little olive oil.",
    ingredients: [
      { item: "Salmon fillet", quantity: "180g" },
      { item: "Wild rice", quantity: "60g (dry)" },
      { item: "Mixed vegetables", quantity: "180g" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Lemon", quantity: "1/2" },
    ],
  },
  "Pork tenderloin with sweet potato and spinach": {
    instructions: "Rub pork with garlic, rosemary, olive oil. Roast at 190°C for 20-25 min. Roast sweet potato alongside. Sauté spinach with garlic in olive oil.",
    ingredients: [
      { item: "Pork tenderloin", quantity: "180g" },
      { item: "Sweet potato", quantity: "200g" },
      { item: "Baby spinach", quantity: "120g" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Dried rosemary", quantity: "1 tsp" },
    ],
  },
  "Turkey meatballs with wholemeal spaghetti and marinara": {
    instructions: "Mix turkey mince with egg, breadcrumbs, garlic, and herbs. Shape into balls and bake at 190°C for 18-20 min. Serve over cooked wholemeal spaghetti with marinara sauce.",
    ingredients: [
      { item: "Lean turkey mince", quantity: "180g" },
      { item: "Wholemeal spaghetti", quantity: "70g (dry)" },
      { item: "Passata or marinara", quantity: "150ml" },
      { item: "Egg", quantity: "1" },
      { item: "Breadcrumbs", quantity: "2 tbsp" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  "Chicken fajitas with brown rice and black beans": {
    instructions: "Slice chicken and season with cumin, paprika, garlic. Stir-fry with sliced peppers and onion. Serve over brown rice with drained black beans.",
    ingredients: [
      { item: "Chicken breast", quantity: "180g" },
      { item: "Brown rice", quantity: "60g (dry)" },
      { item: "Black beans", quantity: "100g (cooked)" },
      { item: "Bell peppers", quantity: "150g" },
      { item: "Onion", quantity: "1/2" },
      { item: "Ground cumin & paprika", quantity: "1 tsp each" },
    ],
  },
  "Grilled white fish with quinoa and roasted vegetables": {
    instructions: "Season fish with lemon, olive oil, salt. Grill 3-4 min each side. Cook quinoa per packet. Roast vegetables at 200°C for 20 min.",
    ingredients: [
      { item: "White fish fillet (cod/haddock)", quantity: "200g" },
      { item: "Quinoa", quantity: "60g (dry)" },
      { item: "Courgette", quantity: "1 small" },
      { item: "Cherry tomatoes", quantity: "100g" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Lemon", quantity: "1/2" },
    ],
  },
  "Lean lamb stir-fry with brown rice and bok choy": {
    instructions: "Slice lean lamb and marinate in soy, ginger, and garlic for 10 min. Stir-fry 3-4 min. Add bok choy and cook 2 more min. Serve over brown rice.",
    ingredients: [
      { item: "Lean lamb leg strips", quantity: "180g" },
      { item: "Brown rice", quantity: "60g (dry)" },
      { item: "Bok choy", quantity: "2 heads" },
      { item: "Soy sauce", quantity: "1.5 tbsp" },
      { item: "Fresh ginger", quantity: "1 tsp (grated)" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  // ── Snacks ──────────────────────────────────────────────────────────────────
  "Protein bar and apple": {
    instructions: "Enjoy a quality protein bar alongside a fresh apple for a balanced snack.",
    ingredients: [
      { item: "Protein bar (20g+ protein)", quantity: "1" },
      { item: "Apple", quantity: "1 medium" },
    ],
  },
  "Greek yogurt with granola": {
    instructions: "Spoon Greek yogurt into a bowl or container. Top with granola and eat immediately.",
    ingredients: [
      { item: "Greek yogurt", quantity: "150g" },
      { item: "Granola", quantity: "40g" },
    ],
  },
  "Trail mix and banana": {
    instructions: "Combine nuts and dried fruit in a small bag for a portable snack. Eat alongside a banana.",
    ingredients: [
      { item: "Almonds", quantity: "15g" },
      { item: "Cashews", quantity: "15g" },
      { item: "Dried cranberries", quantity: "15g" },
      { item: "Banana", quantity: "1 medium" },
    ],
  },
  "Cottage cheese with berries": {
    instructions: "Spoon cottage cheese into a bowl and top with fresh mixed berries.",
    ingredients: [
      { item: "Low-fat cottage cheese", quantity: "150g" },
      { item: "Mixed berries", quantity: "100g" },
    ],
  },
  "Peanut butter and whole grain crackers": {
    instructions: "Spread peanut butter evenly on whole grain crackers for a filling snack.",
    ingredients: [
      { item: "Peanut butter (natural)", quantity: "2 tbsp" },
      { item: "Whole grain crackers", quantity: "8 crackers" },
    ],
  },
  "Hard-boiled eggs and almonds": {
    instructions: "Boil eggs 8-10 min, peel and slice. Serve alongside a small handful of almonds.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "Almonds", quantity: "25g" },
      { item: "Salt (optional)", quantity: "pinch" },
    ],
  },
  "Tuna on rice cakes": {
    instructions: "Drain tuna and mix with a little lemon juice. Spoon onto rice cakes.",
    ingredients: [
      { item: "Canned tuna in water", quantity: "100g (drained)" },
      { item: "Rice cakes", quantity: "3" },
      { item: "Lemon juice", quantity: "1 tsp" },
      { item: "Black pepper", quantity: "to taste" },
    ],
  },
  "Edamame with sea salt": {
    instructions: "Boil or microwave edamame per packet instructions. Drain and toss with sea salt.",
    ingredients: [
      { item: "Edamame (shelled or in pods)", quantity: "150g" },
      { item: "Sea salt", quantity: "1/4 tsp" },
    ],
  },

  // ── Fancy Breakfasts ───────────────────────────────────────────────────────
  "Shakshuka with poached eggs and crusty sourdough": {
    instructions: "Sauté onion, garlic and peppers until soft. Add cumin, paprika and tinned tomatoes; simmer 10 min. Make wells in the sauce and crack in eggs. Cover and cook 5-7 min until whites are set. Finish with fresh herbs. Serve with sourdough.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "Tinned chopped tomatoes", quantity: "400g tin" },
      { item: "Red pepper", quantity: "1" },
      { item: "Onion", quantity: "1/2" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Ground cumin & paprika", quantity: "1 tsp each" },
      { item: "Sourdough bread", quantity: "2 slices" },
      { item: "Fresh coriander or parsley", quantity: "handful" },
    ],
  },
  "Avocado toast with poached eggs and everything bagel seasoning": {
    instructions: "Toast bread. Mash avocado with lemon juice, salt and pepper. Spread on toast. Poach eggs in simmering water with a splash of vinegar for 3-4 min. Place on top and sprinkle with everything bagel seasoning.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "Sourdough or seeded bread", quantity: "2 slices" },
      { item: "Ripe avocado", quantity: "1" },
      { item: "Lemon juice", quantity: "1 tsp" },
      { item: "Everything bagel seasoning", quantity: "1 tsp" },
      { item: "Chilli flakes (optional)", quantity: "pinch" },
    ],
  },
  "Smoked salmon bagel with cream cheese, capers and dill": {
    instructions: "Split and toast the bagel. Spread generously with cream cheese. Layer on smoked salmon, capers, thinly sliced red onion and fresh dill. Finish with a squeeze of lemon.",
    ingredients: [
      { item: "Smoked salmon", quantity: "80g" },
      { item: "Whole grain bagel", quantity: "1" },
      { item: "Cream cheese", quantity: "2 tbsp" },
      { item: "Capers", quantity: "1 tbsp" },
      { item: "Red onion, thinly sliced", quantity: "a few rings" },
      { item: "Fresh dill", quantity: "small handful" },
      { item: "Lemon", quantity: "1/4" },
    ],
  },
  "Bircher muesli with apple, toasted hazelnuts and pomegranate": {
    instructions: "Combine oats, grated apple and yogurt with a little honey. Refrigerate overnight. Top with toasted hazelnuts, pomegranate seeds and a drizzle of honey before serving.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Greek yogurt", quantity: "100g" },
      { item: "Apple, grated", quantity: "1/2" },
      { item: "Hazelnuts, toasted and chopped", quantity: "25g" },
      { item: "Pomegranate seeds", quantity: "2 tbsp" },
      { item: "Honey", quantity: "1 tsp" },
      { item: "Milk or apple juice", quantity: "60ml" },
    ],
  },
  "Savory crepes with goat cheese, spinach and sun-dried tomatoes": {
    instructions: "Make thin crepes from flour, egg and milk. Wilt spinach in a pan with garlic. Fill each crepe with crumbled goat cheese, wilted spinach and sun-dried tomatoes. Fold and heat through in the pan.",
    ingredients: [
      { item: "Plain flour", quantity: "60g" },
      { item: "Egg", quantity: "1" },
      { item: "Milk", quantity: "150ml" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Goat cheese", quantity: "50g" },
      { item: "Sun-dried tomatoes", quantity: "4" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  "Eggs Benedict with Canadian bacon and light hollandaise": {
    instructions: "Toast English muffins. Pan-fry Canadian bacon 2 min each side. Poach eggs 3-4 min. Make a quick hollandaise by whisking egg yolk with lemon juice over low heat, then slowly drizzle in melted butter. Assemble and top with hollandaise.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "English muffins", quantity: "1 (split)" },
      { item: "Canadian bacon", quantity: "2 slices" },
      { item: "Butter", quantity: "30g (for hollandaise)" },
      { item: "Egg yolk", quantity: "1 (for hollandaise)" },
      { item: "Lemon juice", quantity: "1 tsp" },
    ],
  },
  "Coconut overnight oats with mango, lime and toasted coconut": {
    instructions: "Mix oats with coconut milk, chia seeds and maple syrup. Refrigerate overnight. In the morning, top with diced fresh mango, lime zest and toasted coconut flakes.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Coconut milk", quantity: "150ml" },
      { item: "Chia seeds", quantity: "1 tbsp" },
      { item: "Ripe mango, diced", quantity: "1/2" },
      { item: "Toasted coconut flakes", quantity: "2 tbsp" },
      { item: "Lime zest", quantity: "1/2 lime" },
      { item: "Maple syrup", quantity: "1 tsp" },
    ],
  },
  "Huevos rancheros with black beans and pico de gallo": {
    instructions: "Warm tortillas in a dry pan. Fry eggs sunny-side-up. Heat black beans with cumin and garlic. Make pico de gallo by combining diced tomato, onion, jalapeño and coriander. Assemble tortillas with beans, egg and pico de gallo.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "Corn tortillas", quantity: "2" },
      { item: "Black beans", quantity: "100g (cooked)" },
      { item: "Tomatoes, diced", quantity: "2" },
      { item: "Red onion, diced", quantity: "1/4" },
      { item: "Jalapeño", quantity: "1/2 (optional)" },
      { item: "Fresh coriander", quantity: "small handful" },
      { item: "Ground cumin", quantity: "1/2 tsp" },
    ],
  },

  // ── Fancy Lunches ──────────────────────────────────────────────────────────
  "Chicken shawarma bowl with hummus, tabbouleh and flatbread": {
    instructions: "Marinate chicken in olive oil, cumin, coriander, turmeric and garlic. Grill or pan-fry until cooked through. Make tabbouleh with bulgur wheat, parsley, tomato and lemon. Serve over hummus with warm flatbread.",
    ingredients: [
      { item: "Chicken thigh (boneless)", quantity: "180g" },
      { item: "Hummus", quantity: "3 tbsp" },
      { item: "Bulgur wheat", quantity: "50g (dry)" },
      { item: "Fresh parsley", quantity: "large handful" },
      { item: "Cherry tomatoes", quantity: "80g" },
      { item: "Flatbread", quantity: "1 small" },
      { item: "Cumin, coriander, turmeric", quantity: "1 tsp each" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
    ],
  },
  "Pan-seared tuna nicoise with green beans and soft-boiled egg": {
    instructions: "Sear tuna steak in a hot pan with olive oil, 90 sec each side (keep it pink). Blanch green beans. Boil egg 6 min (jammy). Arrange over mixed leaves with olives, cherry tomatoes and a Dijon-lemon dressing.",
    ingredients: [
      { item: "Fresh tuna steak", quantity: "160g" },
      { item: "Egg", quantity: "1" },
      { item: "Green beans", quantity: "100g" },
      { item: "Mixed leaves", quantity: "60g" },
      { item: "Cherry tomatoes", quantity: "80g" },
      { item: "Kalamata olives", quantity: "8" },
      { item: "Dijon mustard", quantity: "1 tsp" },
      { item: "Olive oil & lemon", quantity: "1.5 tbsp / 1 tbsp" },
    ],
  },
  "Thai beef salad with glass noodles, mint and chilli-lime dressing": {
    instructions: "Sear beef steak, slice thinly. Soak glass noodles per packet. Make dressing with fish sauce, lime juice, palm sugar and chilli. Toss with noodles, beef, cucumber, fresh mint and coriander.",
    ingredients: [
      { item: "Lean beef steak", quantity: "160g" },
      { item: "Glass noodles", quantity: "50g (dry)" },
      { item: "Cucumber", quantity: "1/2" },
      { item: "Fresh mint and coriander", quantity: "large handful" },
      { item: "Fish sauce", quantity: "1.5 tbsp" },
      { item: "Lime juice", quantity: "2 tbsp" },
      { item: "Palm sugar or honey", quantity: "1 tsp" },
      { item: "Red chilli", quantity: "1 (deseeded)" },
    ],
  },
  "Mediterranean stuffed peppers with couscous and feta": {
    instructions: "Halve peppers and roast at 200°C for 20 min. Cook couscous and mix with sun-dried tomatoes, olives, crumbled feta and herbs. Fill peppers and bake a further 10 min.",
    ingredients: [
      { item: "Bell peppers", quantity: "2 large" },
      { item: "Couscous", quantity: "60g (dry)" },
      { item: "Feta cheese", quantity: "40g" },
      { item: "Sun-dried tomatoes", quantity: "4" },
      { item: "Kalamata olives", quantity: "8" },
      { item: "Fresh basil or oregano", quantity: "small handful" },
      { item: "Olive oil", quantity: "1 tbsp" },
    ],
  },
  "Prawn and avocado salad with lime, chilli and mixed grains": {
    instructions: "Cook prawns in a hot pan with garlic and chilli, 2 min each side. Mix cooked grains with lime dressing, sliced avocado, cucumber and coriander. Top with prawns.",
    ingredients: [
      { item: "Raw prawns", quantity: "180g (peeled)" },
      { item: "Mixed grains (quinoa, brown rice)", quantity: "60g (dry)" },
      { item: "Avocado", quantity: "1/2" },
      { item: "Cucumber", quantity: "1/3" },
      { item: "Fresh coriander", quantity: "small handful" },
      { item: "Lime juice", quantity: "1.5 tbsp" },
      { item: "Red chilli", quantity: "1/2" },
    ],
  },
  "Chicken souvlaki wrap with tzatziki and roasted vegetables": {
    instructions: "Marinate chicken in olive oil, oregano, garlic and lemon. Grill until cooked through and slightly charred. Roast peppers and courgette. Make tzatziki with yogurt, cucumber, garlic and dill. Assemble in warm flatbread.",
    ingredients: [
      { item: "Chicken breast", quantity: "180g" },
      { item: "Flatbread or pitta", quantity: "1 large" },
      { item: "Greek yogurt", quantity: "3 tbsp" },
      { item: "Cucumber, grated", quantity: "1/4" },
      { item: "Bell peppers and courgette", quantity: "150g combined" },
      { item: "Dried oregano", quantity: "1 tsp" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  "Spiced chickpea and spinach curry with basmati rice": {
    instructions: "Sauté onion, garlic and ginger until soft. Add garam masala, cumin and coriander. Stir in chopped tomatoes and chickpeas; simmer 15 min. Wilt in spinach. Serve with fluffy basmati rice.",
    ingredients: [
      { item: "Chickpeas", quantity: "200g (cooked)" },
      { item: "Baby spinach", quantity: "100g" },
      { item: "Basmati rice", quantity: "60g (dry)" },
      { item: "Tinned chopped tomatoes", quantity: "200g" },
      { item: "Onion", quantity: "1/2" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Garam masala, cumin, coriander", quantity: "1 tsp each" },
    ],
  },
  "Roasted red pepper and lentil soup with sourdough": {
    instructions: "Roast red peppers at 220°C for 25 min, peel. Sauté onion and garlic, add red lentils, roasted peppers, stock and smoked paprika. Simmer 20 min then blend until smooth. Serve with a drizzle of olive oil and crusty sourdough.",
    ingredients: [
      { item: "Red peppers", quantity: "2 large" },
      { item: "Red lentils", quantity: "80g" },
      { item: "Vegetable stock", quantity: "600ml" },
      { item: "Onion", quantity: "1/2" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Smoked paprika", quantity: "1 tsp" },
      { item: "Sourdough bread", quantity: "1 slice" },
    ],
  },

  // ── Fancy Dinners ──────────────────────────────────────────────────────────
  "Herb-crusted salmon with lemon risotto and asparagus": {
    instructions: "Press a mix of breadcrumbs, parsley, lemon zest and olive oil onto the salmon. Bake at 200°C for 14-16 min. Make risotto with arborio rice, white wine, lemon juice and parmesan. Roast asparagus alongside the salmon.",
    ingredients: [
      { item: "Salmon fillet", quantity: "180g" },
      { item: "Arborio rice", quantity: "70g (dry)" },
      { item: "Asparagus", quantity: "120g" },
      { item: "White wine", quantity: "60ml" },
      { item: "Parmesan, grated", quantity: "25g" },
      { item: "Lemon", quantity: "1" },
      { item: "Fresh parsley", quantity: "small handful" },
      { item: "Breadcrumbs", quantity: "2 tbsp" },
    ],
  },
  "Moroccan lamb tagine with apricots, couscous and harissa": {
    instructions: "Brown lamb pieces in a tagine or casserole. Add onion, garlic, ras el hanout, cinnamon and chopped tomatoes. Braise 45 min. Add dried apricots last 15 min. Serve over couscous with a spoonful of harissa.",
    ingredients: [
      { item: "Lean lamb shoulder, cubed", quantity: "180g" },
      { item: "Couscous", quantity: "70g (dry)" },
      { item: "Dried apricots", quantity: "6" },
      { item: "Tinned tomatoes", quantity: "200g" },
      { item: "Ras el hanout", quantity: "1.5 tsp" },
      { item: "Cinnamon", quantity: "1/4 tsp" },
      { item: "Harissa paste", quantity: "1 tsp" },
    ],
  },
  "Thai green chicken curry with jasmine rice and bok choy": {
    instructions: "Fry green curry paste in coconut oil for 1 min. Add sliced chicken and cook 5 min. Pour in coconut milk and simmer 15 min. Add bok choy last 3 min. Serve over jasmine rice with fresh basil and lime.",
    ingredients: [
      { item: "Chicken breast, sliced", quantity: "180g" },
      { item: "Jasmine rice", quantity: "70g (dry)" },
      { item: "Bok choy", quantity: "2 heads" },
      { item: "Light coconut milk", quantity: "200ml" },
      { item: "Green curry paste", quantity: "1.5 tbsp" },
      { item: "Fresh basil", quantity: "small handful" },
      { item: "Lime", quantity: "1/2" },
    ],
  },
  "Seared duck breast with sweet potato puree and cherry jus": {
    instructions: "Score duck skin and season well. Sear skin-down in a cold pan, then increase heat — 8 min skin side, 4 min flesh side. Rest 5 min. Boil sweet potato, mash with butter. Reduce chicken stock with cherries and a splash of red wine for jus.",
    ingredients: [
      { item: "Duck breast", quantity: "180g" },
      { item: "Sweet potato", quantity: "250g" },
      { item: "Fresh or frozen cherries", quantity: "80g" },
      { item: "Chicken stock", quantity: "100ml" },
      { item: "Red wine", quantity: "2 tbsp" },
      { item: "Butter", quantity: "1 tsp" },
    ],
  },
  "Pan-seared sea bass with chorizo, white beans and gremolata": {
    instructions: "Sauté diced chorizo until crispy. Add cannellini beans and a little stock; simmer 5 min. Make gremolata with lemon zest, garlic and parsley. Sear sea bass fillets skin-down for 4 min, flip 1 min. Serve over the bean stew and top with gremolata.",
    ingredients: [
      { item: "Sea bass fillets", quantity: "180g" },
      { item: "Chorizo, diced", quantity: "40g" },
      { item: "Cannellini beans", quantity: "150g (cooked)" },
      { item: "Chicken stock", quantity: "80ml" },
      { item: "Lemon zest", quantity: "1 lemon" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Fresh flat-leaf parsley", quantity: "small handful" },
    ],
  },
  "Miso-glazed cod with edamame fried rice and pickled ginger": {
    instructions: "Mix white miso, mirin, honey and soy. Marinate cod 30 min. Grill under the broiler for 8-10 min. Stir-fry cooked rice with edamame, egg, soy and sesame oil. Serve cod over fried rice with pickled ginger on the side.",
    ingredients: [
      { item: "Cod fillet", quantity: "180g" },
      { item: "White miso paste", quantity: "1.5 tbsp" },
      { item: "Mirin", quantity: "1 tbsp" },
      { item: "Cooked brown rice", quantity: "150g" },
      { item: "Edamame", quantity: "80g" },
      { item: "Egg", quantity: "1" },
      { item: "Pickled ginger", quantity: "1 tbsp" },
      { item: "Sesame oil & soy sauce", quantity: "1 tsp each" },
    ],
  },
  "Chicken piccata with capers, lemon butter sauce and linguine": {
    instructions: "Pound chicken breasts thin, dredge in flour. Pan-fry in olive oil 3-4 min each side. Remove and make sauce in same pan with white wine, lemon juice, capers and a knob of butter. Cook linguine al dente. Serve chicken over pasta with the sauce.",
    ingredients: [
      { item: "Chicken breast, pounded thin", quantity: "180g" },
      { item: "Linguine", quantity: "70g (dry)" },
      { item: "Capers", quantity: "1.5 tbsp" },
      { item: "White wine", quantity: "60ml" },
      { item: "Lemon juice", quantity: "2 tbsp" },
      { item: "Butter", quantity: "1.5 tbsp" },
      { item: "Plain flour (for dredging)", quantity: "2 tbsp" },
    ],
  },
  "Beef tenderloin with dauphinoise potato and green peppercorn sauce": {
    instructions: "Thinly slice potatoes and layer with cream, garlic and gruyère. Bake at 170°C for 60 min. Sear beef medallions in a very hot pan, 3 min each side for medium-rare. Rest 5 min. Make sauce by searing the pan with beef stock, cream and green peppercorns.",
    ingredients: [
      { item: "Beef tenderloin medallion", quantity: "180g" },
      { item: "Potatoes, thinly sliced", quantity: "250g" },
      { item: "Double cream", quantity: "100ml" },
      { item: "Gruyère, grated", quantity: "25g" },
      { item: "Beef stock", quantity: "80ml" },
      { item: "Green peppercorns in brine", quantity: "1 tbsp" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },

  // ── Fancy Snacks ───────────────────────────────────────────────────────────
  "Baba ganoush with toasted pita and cucumber": {
    instructions: "Char aubergine directly over a gas flame or under the grill until completely blackened. Scoop out flesh and blend with tahini, garlic, lemon juice and olive oil. Serve with toasted pitta triangles and sliced cucumber.",
    ingredients: [
      { item: "Aubergine (eggplant)", quantity: "1 large" },
      { item: "Tahini", quantity: "1.5 tbsp" },
      { item: "Lemon juice", quantity: "1.5 tbsp" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Pitta bread", quantity: "1 (toasted)" },
      { item: "Cucumber", quantity: "1/3" },
    ],
  },
  "Whipped ricotta with honey, walnuts and pomegranate": {
    instructions: "Blend ricotta with a little salt and lemon zest until very smooth. Spread into a bowl. Top with a generous drizzle of honey, chopped toasted walnuts and pomegranate seeds.",
    ingredients: [
      { item: "Ricotta cheese", quantity: "120g" },
      { item: "Honey", quantity: "1.5 tbsp" },
      { item: "Walnuts, toasted and chopped", quantity: "20g" },
      { item: "Pomegranate seeds", quantity: "2 tbsp" },
      { item: "Lemon zest", quantity: "pinch" },
    ],
  },
  "Smoked salmon and cream cheese on rye crispbreads": {
    instructions: "Spread cream cheese generously onto rye crispbreads. Top with smoked salmon, a squeeze of lemon and fresh dill. Finish with black pepper.",
    ingredients: [
      { item: "Smoked salmon", quantity: "60g" },
      { item: "Cream cheese", quantity: "2 tbsp" },
      { item: "Rye crispbreads", quantity: "3" },
      { item: "Fresh dill", quantity: "small handful" },
      { item: "Lemon juice", quantity: "squeeze" },
    ],
  },
  "Roasted spiced chickpeas with tahini dip": {
    instructions: "Drain and dry chickpeas well. Toss with olive oil, smoked paprika, cumin and salt. Roast at 200°C for 25-30 min until crispy. Make dip by stirring tahini with lemon juice, garlic and a little water.",
    ingredients: [
      { item: "Chickpeas", quantity: "200g (cooked, drained)" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Smoked paprika & cumin", quantity: "1/2 tsp each" },
      { item: "Tahini", quantity: "1.5 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Garlic clove", quantity: "1/2" },
    ],
  },
  "Caprese skewers with fresh mozzarella and basil pesto": {
    instructions: "Thread fresh mozzarella balls, cherry tomatoes and basil leaves onto small skewers. Drizzle with store-bought or homemade pesto and a little balsamic glaze.",
    ingredients: [
      { item: "Fresh mozzarella (bocconcini)", quantity: "100g" },
      { item: "Cherry tomatoes", quantity: "100g" },
      { item: "Fresh basil leaves", quantity: "12 leaves" },
      { item: "Basil pesto", quantity: "1 tbsp" },
      { item: "Balsamic glaze", quantity: "1 tsp" },
    ],
  },
  "Prosciutto-wrapped melon with rocket": {
    instructions: "Cut melon into wedges and remove the skin. Wrap each wedge with a slice of prosciutto. Arrange over rocket leaves and finish with a drizzle of olive oil and cracked black pepper.",
    ingredients: [
      { item: "Melon (cantaloupe or honeydew)", quantity: "1/4 melon" },
      { item: "Prosciutto", quantity: "3 slices" },
      { item: "Rocket (arugula)", quantity: "30g" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Black pepper", quantity: "to taste" },
    ],
  },
  "Nut butter energy balls with oats, dates and dark chocolate": {
    instructions: "Blend pitted dates until sticky. Mix with oats, almond butter and a pinch of salt. Fold in dark chocolate chips. Roll into balls and refrigerate for at least 30 min before eating.",
    ingredients: [
      { item: "Medjool dates, pitted", quantity: "6" },
      { item: "Rolled oats", quantity: "50g" },
      { item: "Almond butter", quantity: "1.5 tbsp" },
      { item: "Dark chocolate chips", quantity: "15g" },
      { item: "Sea salt", quantity: "pinch" },
    ],
  },
  "Tuna tartare on cucumber rounds with sesame and soy": {
    instructions: "Finely dice sushi-grade tuna. Mix with soy sauce, sesame oil, lime juice and a little sriracha. Slice cucumber into rounds. Top each with a small spoonful of tartare and garnish with sesame seeds and microgreens.",
    ingredients: [
      { item: "Sushi-grade tuna", quantity: "120g" },
      { item: "Cucumber", quantity: "1/2" },
      { item: "Soy sauce", quantity: "1 tbsp" },
      { item: "Sesame oil", quantity: "1 tsp" },
      { item: "Lime juice", quantity: "1 tsp" },
      { item: "Sriracha", quantity: "1/4 tsp" },
      { item: "Sesame seeds & microgreens", quantity: "1 tsp / small handful" },
    ],
  },

  // ── Gourmet Breakfasts ──────────────────────────────────────────────────────
  "Croque Madame with Gruyère, smoked ham and fried egg": {
    instructions: "Make a béchamel by melting butter, whisking in flour then milk; season well. Spread on both slices of bread. Layer smoked ham and Gruyère between slices. Top with more béchamel and cheese. Grill until golden and bubbling. Meanwhile fry an egg in butter until the white is set. Place on top of the toast and serve immediately.",
    ingredients: [
      { item: "Sourdough or thick white bread", quantity: "2 slices" },
      { item: "Smoked cooked ham", quantity: "60g" },
      { item: "Gruyère cheese, grated", quantity: "50g" },
      { item: "Egg", quantity: "1" },
      { item: "Butter", quantity: "15g" },
      { item: "Plain flour", quantity: "1 tbsp" },
      { item: "Whole milk", quantity: "80ml" },
      { item: "Dijon mustard", quantity: "1 tsp" },
    ],
  },
  "Slow scrambled eggs with crème fraîche, chives and smoked trout on rye": {
    instructions: "Whisk eggs with crème fraîche and a pinch of salt. Melt butter in a non-stick pan on the lowest heat. Add eggs and stir very gently and continuously for 8–10 minutes until softly set and creamy. Remove from heat just before fully done. Serve on toasted rye with flaked smoked trout and fresh chives.",
    ingredients: [
      { item: "Eggs", quantity: "3" },
      { item: "Crème fraîche", quantity: "1 tbsp" },
      { item: "Smoked trout fillets", quantity: "80g" },
      { item: "Rye bread", quantity: "2 slices" },
      { item: "Butter", quantity: "1 tsp" },
      { item: "Fresh chives, chopped", quantity: "1 tbsp" },
      { item: "Salt & black pepper", quantity: "to taste" },
    ],
  },
  "Ricotta pancakes with blueberry compote and lemon curd": {
    instructions: "Separate eggs. Mix yolks with ricotta, flour, baking powder and lemon zest. Whisk whites to soft peaks and fold in gently. Cook spoonfuls in a buttered pan on low-medium heat, 2–3 min per side. For the compote, simmer blueberries with sugar and a squeeze of lemon for 5 minutes. Serve pancakes topped with compote and a spoonful of lemon curd.",
    ingredients: [
      { item: "Ricotta cheese", quantity: "125g" },
      { item: "Eggs", quantity: "2 (separated)" },
      { item: "Plain flour", quantity: "40g" },
      { item: "Baking powder", quantity: "1/2 tsp" },
      { item: "Lemon", quantity: "1 (zest + juice)" },
      { item: "Fresh or frozen blueberries", quantity: "100g" },
      { item: "Lemon curd", quantity: "2 tbsp" },
      { item: "Butter", quantity: "1 tsp" },
      { item: "Caster sugar", quantity: "1 tsp" },
    ],
  },
  "Brioche French toast with mascarpone, caramelised banana and maple syrup": {
    instructions: "Whisk eggs with milk and a pinch of cinnamon. Dip brioche slices and pan-fry in butter on medium heat until golden, 2–3 min each side. Meanwhile, halve the banana and fry cut-side down in a little butter and a pinch of sugar until caramelised, about 2 minutes. Serve toast topped with a spoonful of mascarpone, the caramelised banana and a drizzle of maple syrup.",
    ingredients: [
      { item: "Brioche", quantity: "2 thick slices" },
      { item: "Eggs", quantity: "2" },
      { item: "Whole milk", quantity: "3 tbsp" },
      { item: "Banana", quantity: "1" },
      { item: "Mascarpone", quantity: "2 tbsp" },
      { item: "Maple syrup", quantity: "1 tbsp" },
      { item: "Butter", quantity: "1 tbsp" },
      { item: "Ground cinnamon", quantity: "pinch" },
    ],
  },
  "Baked eggs in tomato and chorizo sauce with crusty sourdough": {
    instructions: "Slice chorizo and fry in a medium oven-proof frying pan for 2 minutes until the oils release. Add sliced garlic and cook 1 minute. Pour in tinned tomatoes, season with smoked paprika, salt and pepper, and simmer 8–10 min. Make wells in the sauce and crack in the eggs. Bake in a 190°C oven for 8–10 minutes until the whites are set but yolks remain runny. Scatter with parsley and serve with sourdough.",
    ingredients: [
      { item: "Cooking chorizo", quantity: "80g, sliced" },
      { item: "Tinned chopped tomatoes", quantity: "400g tin" },
      { item: "Eggs", quantity: "2" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Sourdough bread", quantity: "2 slices" },
      { item: "Fresh parsley", quantity: "small handful" },
    ],
  },
  "Poached eggs with wilted spinach, lemon hollandaise and smoked salmon": {
    instructions: "Make a quick hollandaise: whisk 2 egg yolks with 1 tsp lemon juice in a heatproof bowl over simmering water until thick. Slowly whisk in melted butter until glossy; season. Wilt spinach in a pan with a little butter. Poach eggs in simmering water with a splash of vinegar, 3–4 min. Toast English muffins. Layer spinach, smoked salmon and egg, then spoon hollandaise generously over the top.",
    ingredients: [
      { item: "Eggs", quantity: "2" },
      { item: "Smoked salmon", quantity: "80g" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Sourdough or English muffin", quantity: "1 muffin / 2 slices" },
      { item: "Butter", quantity: "50g (for hollandaise)" },
      { item: "Egg yolks", quantity: "2 (for hollandaise)" },
      { item: "Lemon juice", quantity: "1.5 tsp" },
      { item: "White wine vinegar", quantity: "1 tsp (for poaching)" },
    ],
  },
  "Smoked salmon and cream cheese omelette with chives and sourdough": {
    instructions: "Whisk 3 eggs with a pinch of salt and pepper. Melt butter in a non-stick pan over medium heat. Pour in eggs and draw the edges in with a spatula until just set but still creamy on top. Add cream cheese and smoked salmon to one half, fold over and slide onto a plate. Finish with snipped chives and serve with toasted sourdough.",
    ingredients: [
      { item: "Eggs", quantity: "3" },
      { item: "Smoked salmon", quantity: "60g" },
      { item: "Cream cheese", quantity: "1.5 tbsp" },
      { item: "Fresh chives, snipped", quantity: "1 tbsp" },
      { item: "Butter", quantity: "1 tsp" },
      { item: "Sourdough bread", quantity: "1 thick slice" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Warm spiced oats with poached pear, cardamom cream and toasted pistachios": {
    instructions: "Halve pear and simmer gently in water with a little honey and a star anise for 8 min until tender. Cook oats with milk, ground cinnamon and cardamom until creamy. Whip crème fraîche with a pinch of cardamom. Serve oats topped with the poached pear, a dollop of cardamom cream and a scatter of toasted pistachios.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Whole milk", quantity: "220ml" },
      { item: "Ripe pear", quantity: "1" },
      { item: "Crème fraîche", quantity: "2 tbsp" },
      { item: "Pistachios, toasted and roughly chopped", quantity: "20g" },
      { item: "Ground cardamom", quantity: "1/4 tsp" },
      { item: "Ground cinnamon", quantity: "1/4 tsp" },
      { item: "Honey", quantity: "1 tsp" },
      { item: "Star anise", quantity: "1" },
    ],
  },

  // ── Gourmet Lunches ─────────────────────────────────────────────────────────
  "Pan-seared salmon with asparagus, lemon caper butter and new potatoes": {
    instructions: "Boil new potatoes until tender, drain and crush lightly with butter. Trim asparagus and blanch 3 min. Season salmon skin-side down, sear in a hot pan with oil, 4 min; flip and cook 2 more min. Remove fish. Add butter, capers and lemon juice to the pan and swirl for 1 min. Plate potatoes and asparagus, lay salmon on top and pour over the caper butter.",
    ingredients: [
      { item: "Salmon fillet", quantity: "200g" },
      { item: "New potatoes", quantity: "200g" },
      { item: "Asparagus spears", quantity: "120g" },
      { item: "Butter", quantity: "20g" },
      { item: "Capers", quantity: "1 tbsp" },
      { item: "Lemon", quantity: "1/2" },
      { item: "Olive oil", quantity: "1 tbsp" },
    ],
  },
  "Seared sea bass fillet with chorizo, butter beans and wilted spinach": {
    instructions: "Fry sliced chorizo until crispy; set aside, keeping the oil in the pan. Add garlic and butter beans, cook 2 min. Add white wine, let it reduce by half, then add baby spinach and stir until wilted. Season the sea bass fillets, score the skin and sear skin-side down in a separate hot pan with oil for 3–4 min until crispy, flip for 1 min. Serve the bean mixture in a shallow bowl topped with the fish and the crispy chorizo.",
    ingredients: [
      { item: "Sea bass fillets", quantity: "200g (2 fillets)" },
      { item: "Cooking chorizo", quantity: "60g, sliced" },
      { item: "Butter beans", quantity: "240g tin, drained" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Dry white wine", quantity: "50ml" },
      { item: "Olive oil", quantity: "1 tbsp" },
    ],
  },
  "Seared scallops with pea purée, crispy pancetta and lemon butter": {
    instructions: "Fry pancetta rashers until crispy; drain and set aside. Blitz peas with butter, mint, salt and a splash of the cooking water until smooth; keep warm. Pat scallops very dry. Heat a pan until very hot, add a little oil and sear scallops 1.5 min per side without moving. Remove, add butter and lemon juice to the pan, swirl to make a sauce. Plate the purée, set scallops on top, drizzle with the lemon butter and crumble over the pancetta.",
    ingredients: [
      { item: "King scallops", quantity: "6 (fresh or defrosted)" },
      { item: "Frozen peas", quantity: "200g" },
      { item: "Pancetta rashers", quantity: "3" },
      { item: "Butter", quantity: "25g" },
      { item: "Fresh mint leaves", quantity: "5 leaves" },
      { item: "Lemon juice", quantity: "1 tsp" },
      { item: "Olive oil", quantity: "1 tsp" },
    ],
  },
  "Grilled ribeye steak salad with blue cheese, walnuts and bitter leaves": {
    instructions: "Bring steak to room temperature. Season generously with salt and pepper. Grill or pan-sear 3–4 min per side for medium-rare; rest 5 minutes. Toast walnuts in a dry pan 2–3 min. Whisk together olive oil, red wine vinegar, Dijon and a little honey for the dressing. Toss chicory and rocket with dressing. Slice the steak and arrange over the leaves. Crumble over blue cheese and scatter walnuts.",
    ingredients: [
      { item: "Ribeye steak", quantity: "200g" },
      { item: "Blue cheese (e.g. Stilton or Gorgonzola)", quantity: "40g" },
      { item: "Walnuts", quantity: "30g" },
      { item: "Chicory or radicchio", quantity: "1 head" },
      { item: "Rocket", quantity: "40g" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Red wine vinegar", quantity: "1 tsp" },
      { item: "Dijon mustard", quantity: "1/2 tsp" },
    ],
  },
  "Crispy duck leg with Puy lentil salad, mustard dressing and watercress": {
    instructions: "Season duck leg generously and roast at 180°C for 60–70 min until the skin is golden and crispy. Cook Puy lentils in stock for 20–25 min until just tender; drain. While warm, toss with shallot, parsley, olive oil, red wine vinegar and wholegrain mustard. Arrange lentils on a plate, top with the duck leg and lay watercress alongside.",
    ingredients: [
      { item: "Duck leg", quantity: "1 (approx 300g)" },
      { item: "Puy lentils", quantity: "80g (dry)" },
      { item: "Watercress", quantity: "50g" },
      { item: "Shallot, finely diced", quantity: "1" },
      { item: "Fresh parsley, chopped", quantity: "small handful" },
      { item: "Wholegrain mustard", quantity: "1 tsp" },
      { item: "Red wine vinegar", quantity: "1 tbsp" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Chicken stock", quantity: "300ml" },
    ],
  },
  "Roasted red pepper and goat cheese tart with dressed rocket salad": {
    instructions: "Unroll a sheet of shop-bought puff pastry. Score a 1cm border all around and prick the centre with a fork. Spread crème fraîche within the border; season. Layer with sliced roasted red peppers (from a jar). Crumble over goat cheese and scatter with thyme leaves. Bake at 200°C for 18–20 min until golden. Toss rocket with olive oil, lemon juice and black pepper. Serve alongside the warm tart.",
    ingredients: [
      { item: "Ready-rolled puff pastry", quantity: "1 sheet (approx 320g)" },
      { item: "Roasted red peppers (jar)", quantity: "150g, drained and sliced" },
      { item: "Soft goat cheese", quantity: "80g" },
      { item: "Crème fraîche", quantity: "2 tbsp" },
      { item: "Fresh thyme", quantity: "few sprigs" },
      { item: "Rocket", quantity: "50g" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Lemon juice", quantity: "1 tsp" },
    ],
  },
  "Warm chicken liver salad with crispy bacon, baby spinach and balsamic": {
    instructions: "Grill or fry bacon rashers until crispy; set aside. Trim chicken livers. Heat olive oil in a pan over high heat and fry livers 2 min per side until browned outside but still slightly pink inside. Deglaze with balsamic vinegar and let it reduce for 30 seconds. Arrange baby spinach on plates, top with livers, crumble over the bacon. Drizzle with the pan juices and any extra olive oil.",
    ingredients: [
      { item: "Chicken livers", quantity: "200g, trimmed" },
      { item: "Bacon rashers", quantity: "3" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Balsamic vinegar", quantity: "1.5 tbsp" },
      { item: "Olive oil", quantity: "1.5 tbsp" },
      { item: "Sourdough bread, toasted", quantity: "1 slice (optional)" },
    ],
  },
  "Seared tuna steak with mango salsa, wild rice and lime crème fraîche": {
    instructions: "Cook wild rice per packet (about 25 min). Make salsa by combining diced mango, red onion, chilli, coriander and lime juice; season. Whisk crème fraîche with lime zest and a pinch of salt. Heat a pan until very hot. Season tuna, brush with oil and sear 1–1.5 min per side (it should remain pink inside). Serve tuna over rice with the salsa on top and a spoonful of lime crème fraîche on the side.",
    ingredients: [
      { item: "Tuna steak", quantity: "180g" },
      { item: "Wild rice blend", quantity: "70g (dry)" },
      { item: "Ripe mango", quantity: "1/2, diced" },
      { item: "Red onion, finely diced", quantity: "1/4" },
      { item: "Red chilli, deseeded and diced", quantity: "1/2" },
      { item: "Fresh coriander, chopped", quantity: "small handful" },
      { item: "Lime", quantity: "1" },
      { item: "Crème fraîche", quantity: "2 tbsp" },
      { item: "Olive oil", quantity: "1 tsp" },
    ],
  },

  // ── Gourmet Dinners ─────────────────────────────────────────────────────────
  "Ribeye steak with truffle butter, dauphinoise potatoes and tenderstem broccoli": {
    instructions: "Make dauphinoise: slice potatoes thinly, layer in a buttered dish with double cream, garlic and seasoning; cover with foil and bake 50 min at 170°C, uncover for last 15 min. Make truffle butter by mixing softened butter with truffle oil, salt and a little garlic. Bring steak to room temp; season generously. Sear in a screaming hot pan 3–4 min each side for medium-rare; rest 5 min. Blanch tenderstem broccoli 3 min. Top steak with a slice of truffle butter.",
    ingredients: [
      { item: "Ribeye steak", quantity: "220g" },
      { item: "Potatoes (e.g. Maris Piper)", quantity: "300g" },
      { item: "Double cream", quantity: "150ml" },
      { item: "Garlic cloves", quantity: "2" },
      { item: "Tenderstem broccoli", quantity: "150g" },
      { item: "Butter", quantity: "40g" },
      { item: "Truffle oil", quantity: "1 tsp" },
    ],
  },
  "Duck breast with cherry and port sauce, potato gratin and wilted greens": {
    instructions: "Score the duck skin in a crosshatch pattern. Place skin-side down in a cold pan, then bring to medium heat. Cook 12–15 min as the fat renders until the skin is golden. Flip and cook 3 min more for medium. Rest 8 min. Meanwhile, make the sauce: deglaze the pan with port, add chicken stock and pitted cherries; reduce by half. For the gratin: layer sliced potato with cream, garlic and cheese; bake at 180°C for 45 min. Wilt greens with butter. Slice duck and plate with the sauce.",
    ingredients: [
      { item: "Duck breast", quantity: "1 (approx 200g)" },
      { item: "Potatoes", quantity: "250g" },
      { item: "Double cream", quantity: "100ml" },
      { item: "Gruyère or cheddar, grated", quantity: "40g" },
      { item: "Port", quantity: "60ml" },
      { item: "Chicken stock", quantity: "100ml" },
      { item: "Fresh or frozen cherries", quantity: "80g, pitted" },
      { item: "Spring greens or Savoy cabbage", quantity: "100g" },
      { item: "Butter", quantity: "1 tbsp" },
    ],
  },
  "Rack of lamb with herb crust, roasted garlic mash and red wine jus": {
    instructions: "Blend breadcrumbs with rosemary, thyme, parsley and a little olive oil. Sear the lamb rack on all sides in a hot pan 3 min. Press the herb crust onto the fat side. Roast at 200°C for 18–20 min for medium-rare. Rest 10 min. Slow-roast a whole garlic bulb alongside. Squeeze the soft garlic into mashed potato with butter and cream. Make the jus: deglaze the roasting tin with red wine and stock, reduce until syrupy.",
    ingredients: [
      { item: "Rack of lamb (6–8 bones)", quantity: "approx 400g" },
      { item: "Potatoes", quantity: "300g" },
      { item: "Garlic bulb", quantity: "1 (plus 2 extra cloves)" },
      { item: "Red wine", quantity: "100ml" },
      { item: "Chicken or lamb stock", quantity: "100ml" },
      { item: "Fresh rosemary & thyme", quantity: "2 sprigs each" },
      { item: "Fresh parsley", quantity: "small handful" },
      { item: "Breadcrumbs", quantity: "30g" },
      { item: "Butter", quantity: "30g" },
      { item: "Double cream", quantity: "2 tbsp" },
    ],
  },
  "Pan-roasted sea bass with saffron mussels, new potatoes and parsley oil": {
    instructions: "Boil new potatoes until tender; halve. Soak saffron in 1 tbsp hot water. Steam mussels: heat shallot, garlic and white wine in a lidded pan, add mussels, cover and cook 3–4 min until opened; discard any that don't open. Strain the liquor and stir in saffron, butter and cream to make a sauce. Season sea bass, score the skin and sear skin-side down in a very hot pan 4 min until crispy, flip 1 min. Blend parsley with olive oil for the parsley oil. Plate potatoes and mussels, lay fish on top, pour over sauce, drizzle with parsley oil.",
    ingredients: [
      { item: "Sea bass fillets", quantity: "200g" },
      { item: "Fresh mussels", quantity: "400g (cleaned)" },
      { item: "New potatoes", quantity: "200g" },
      { item: "Saffron", quantity: "good pinch" },
      { item: "Dry white wine", quantity: "100ml" },
      { item: "Shallot", quantity: "1" },
      { item: "Double cream", quantity: "3 tbsp" },
      { item: "Butter", quantity: "15g" },
      { item: "Fresh flat-leaf parsley", quantity: "large handful" },
      { item: "Olive oil", quantity: "2 tbsp" },
    ],
  },
  "Slow-braised beef short ribs with creamy polenta, gremolata and roasted roots": {
    instructions: "Season short ribs and sear all over in a casserole. Set aside. Fry onion, carrot and celery until soft. Add tomato paste, red wine and stock; return ribs, bring to a simmer, cover and braise at 160°C for 3–3.5 hours until the meat falls off the bone. Roast parsnips and carrots alongside. For polenta: bring salted water to boil, whisk in polenta and stir constantly for 5 min; finish with butter and parmesan. Make gremolata with lemon zest, garlic and parsley. Serve ribs over polenta, with roots and the braising jus.",
    ingredients: [
      { item: "Beef short ribs", quantity: "400g (bone-in)" },
      { item: "Coarse polenta", quantity: "80g" },
      { item: "Parmesan, grated", quantity: "30g" },
      { item: "Parsnips and carrots", quantity: "200g mixed" },
      { item: "Red wine", quantity: "150ml" },
      { item: "Beef stock", quantity: "300ml" },
      { item: "Onion, carrot, celery", quantity: "1 each" },
      { item: "Tomato paste", quantity: "1 tbsp" },
      { item: "Lemon zest, garlic, flat-leaf parsley", quantity: "for gremolata" },
      { item: "Butter", quantity: "20g" },
    ],
  },
  "Chicken supreme with wild mushroom and tarragon cream sauce, pommes purée": {
    instructions: "Sear chicken supremes skin-side down in butter and oil, 5–6 min until golden; flip and roast at 190°C for 15 min. Rest 5 min. For the sauce: sauté shallot, then add sliced mushrooms and cook until any liquid evaporates. Splash in white wine, reduce, then add double cream and fresh tarragon; simmer 5 min. For the purée: boil potatoes, drain well, pass through a ricer; beat in generous butter and warm cream until silky.",
    ingredients: [
      { item: "Chicken supreme (skin-on breast)", quantity: "2 pieces (approx 180g each)" },
      { item: "Chestnut or mixed wild mushrooms", quantity: "150g, sliced" },
      { item: "Double cream", quantity: "100ml" },
      { item: "Dry white wine", quantity: "60ml" },
      { item: "Fresh tarragon leaves", quantity: "1 tbsp" },
      { item: "Potatoes", quantity: "300g" },
      { item: "Butter", quantity: "50g" },
      { item: "Shallot", quantity: "1" },
      { item: "Olive oil", quantity: "1 tbsp" },
    ],
  },
  "Salmon en croûte with spinach and cream cheese filling, lemon dill sauce": {
    instructions: "Wilt spinach with garlic; squeeze out moisture and mix with cream cheese, dill and seasoning. Lay a puff pastry sheet on a baking tray. Place salmon fillet in the centre, top with spinach mixture, fold pastry over and seal the edges. Brush with egg wash and score lightly. Bake at 200°C for 25–30 min until deep golden. Make the sauce: heat crème fraîche gently with lemon juice, zest and fresh dill — do not boil.",
    ingredients: [
      { item: "Salmon fillet (skinless)", quantity: "350g" },
      { item: "Ready-rolled puff pastry", quantity: "1 sheet (approx 320g)" },
      { item: "Baby spinach", quantity: "100g" },
      { item: "Cream cheese", quantity: "80g" },
      { item: "Fresh dill", quantity: "2 tbsp, chopped" },
      { item: "Egg", quantity: "1 (for egg wash)" },
      { item: "Crème fraîche", quantity: "100ml (for sauce)" },
      { item: "Lemon", quantity: "1 (zest and juice)" },
      { item: "Garlic clove", quantity: "1" },
    ],
  },
  "Slow-roasted pork belly with apple and cider jus, roasted roots and mustard greens": {
    instructions: "Score pork belly skin, rub generously with salt, pepper and fennel seeds; refrigerate uncovered overnight if possible. Roast skin-side up at 150°C for 2.5 hours, then increase to 220°C for 20–25 min until crackling is crisp. Roast parsnips and carrots tossed in olive oil alongside at 200°C for 30 min. For the jus: reduce dry cider and chicken stock with a quartered apple and a little thyme; sieve and season. Sauté greens with wholegrain mustard and butter.",
    ingredients: [
      { item: "Pork belly slices or joint", quantity: "400g" },
      { item: "Dry cider", quantity: "150ml" },
      { item: "Chicken stock", quantity: "100ml" },
      { item: "Apple", quantity: "1, cored and quartered" },
      { item: "Parsnips and carrots", quantity: "200g mixed" },
      { item: "Spring greens or kale", quantity: "100g" },
      { item: "Wholegrain mustard", quantity: "1 tsp" },
      { item: "Fennel seeds", quantity: "1 tsp" },
      { item: "Fresh thyme", quantity: "3 sprigs" },
      { item: "Butter", quantity: "15g" },
    ],
  },

  // ── Gourmet Snacks ──────────────────────────────────────────────────────────
  "Parma ham with marinated artichoke hearts and olives": {
    instructions: "Arrange Parma ham slices on a board. Drain artichoke hearts and olives; toss together with a drizzle of olive oil, a squeeze of lemon and black pepper. Serve alongside crusty bread or breadsticks.",
    ingredients: [
      { item: "Parma ham", quantity: "4 slices" },
      { item: "Marinated artichoke hearts (jar)", quantity: "80g, drained" },
      { item: "Mixed olives", quantity: "40g" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Lemon juice", quantity: "1/2 tsp" },
      { item: "Crusty bread or breadsticks", quantity: "to serve" },
    ],
  },
  "Smoked mackerel pâté with dark rye crispbreads and cucumber": {
    instructions: "Flake the smoked mackerel into a bowl, discarding skin and any bones. Beat in cream cheese, lemon juice, horseradish sauce and black pepper until smooth and creamy. Taste and adjust seasoning. Spoon into a small dish. Slice cucumber into rounds. Serve alongside the rye crispbreads and cucumber for dipping and spreading.",
    ingredients: [
      { item: "Smoked mackerel fillet", quantity: "150g" },
      { item: "Cream cheese", quantity: "50g" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Creamed horseradish", quantity: "1 tsp" },
      { item: "Rye crispbreads", quantity: "4" },
      { item: "Cucumber", quantity: "1/3" },
      { item: "Black pepper", quantity: "to taste" },
    ],
  },
  "Crostini with ricotta, honey and toasted walnuts": {
    instructions: "Slice a baguette or sourdough on the diagonal. Brush lightly with olive oil and toast in a hot oven or under the grill for 3–4 min until golden. While warm, spread generously with ricotta. Drizzle with good honey, scatter over the toasted walnuts and finish with a pinch of sea salt and black pepper.",
    ingredients: [
      { item: "Sourdough or baguette", quantity: "3–4 slices" },
      { item: "Ricotta", quantity: "80g" },
      { item: "Walnuts, toasted and roughly chopped", quantity: "25g" },
      { item: "Runny honey", quantity: "1 tbsp" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Sea salt & black pepper", quantity: "to taste" },
    ],
  },
  "Burrata with slow-roasted cherry tomatoes, basil and aged balsamic": {
    instructions: "Toss cherry tomatoes with olive oil, a pinch of sugar, salt and pepper. Spread on a baking tray and slow-roast at 140°C for 40–50 min until wrinkled and sweet. Allow to cool slightly. Place burrata on a plate, arrange warm tomatoes around it, scatter fresh basil leaves, drizzle with the best olive oil you have and finish with a few drops of aged balsamic glaze.",
    ingredients: [
      { item: "Burrata", quantity: "1 ball (approx 125g)" },
      { item: "Cherry tomatoes", quantity: "200g" },
      { item: "Fresh basil leaves", quantity: "handful" },
      { item: "Aged balsamic glaze", quantity: "1 tsp" },
      { item: "Extra virgin olive oil", quantity: "1.5 tbsp" },
      { item: "Sourdough, toasted (optional)", quantity: "1 slice" },
    ],
  },
  "Manchego cheese with quince paste, Marcona almonds and Serrano ham": {
    instructions: "Slice Manchego into thin shards. Slice quince paste into small cubes or spread onto crispbreads. Arrange everything on a board or plate — cheese, quince, a few slices of Serrano ham and a small pile of Marcona almonds. Serve with crispbreads or crackers.",
    ingredients: [
      { item: "Manchego cheese", quantity: "60g" },
      { item: "Quince paste (membrillo)", quantity: "30g" },
      { item: "Marcona almonds", quantity: "25g" },
      { item: "Serrano ham", quantity: "2 slices" },
      { item: "Crispbreads or crackers", quantity: "3–4" },
    ],
  },
  "Smoked salmon blinis with crème fraîche and capers": {
    instructions: "If making blinis from scratch: mix buckwheat flour, plain flour, baking powder, egg and milk to a thick batter; fry small spoonfuls in butter 1–2 min per side until golden. (Shop-bought blinis can be warmed in a low oven.) Top each blini with a small spoonful of crème fraîche, a fold of smoked salmon, a few capers and a tiny squeeze of lemon.",
    ingredients: [
      { item: "Smoked salmon", quantity: "80g" },
      { item: "Blinis (shop-bought or homemade)", quantity: "8" },
      { item: "Crème fraîche", quantity: "3 tbsp" },
      { item: "Capers", quantity: "1 tbsp" },
      { item: "Lemon", quantity: "1/4" },
      { item: "Fresh dill (optional)", quantity: "small sprig" },
    ],
  },
  "Brie with honey, walnuts and sliced pear on crispbreads": {
    instructions: "Toast walnut halves in a dry pan for 2 minutes until lightly golden. Slice pear thinly. Arrange crispbreads on a board. Top each with a slice of ripe Brie, a piece of pear, a walnut half and a small drizzle of runny honey. Finish with a grind of black pepper.",
    ingredients: [
      { item: "Ripe Brie", quantity: "60g, sliced" },
      { item: "Ripe pear", quantity: "1/2, thinly sliced" },
      { item: "Walnuts", quantity: "25g" },
      { item: "Runny honey", quantity: "1.5 tsp" },
      { item: "Crispbreads or water crackers", quantity: "4" },
      { item: "Black pepper", quantity: "to taste" },
    ],
  },
  "Warm rosemary and chilli marinated olives with sourdough": {
    instructions: "Gently warm olive oil in a small pan with crushed garlic, rosemary sprigs, dried chilli flakes and lemon zest for 5 minutes — don't let it fry, just infuse. Pour over drained mixed olives in a bowl and toss well. Serve warm with slices of sourdough for dipping.",
    ingredients: [
      { item: "Mixed olives", quantity: "150g, drained" },
      { item: "Olive oil", quantity: "3 tbsp" },
      { item: "Fresh rosemary", quantity: "2 sprigs" },
      { item: "Garlic clove, crushed", quantity: "1" },
      { item: "Dried chilli flakes", quantity: "1/4 tsp" },
      { item: "Lemon zest", quantity: "1/2 lemon" },
      { item: "Sourdough bread", quantity: "2 slices" },
    ],
  },
  // ── Missing Plant-Based Breakfasts ─────────────────────────────────────────
  "Banana and peanut butter overnight oats": {
    instructions: "In a jar or bowl, combine oats, milk and chia seeds. Stir in peanut butter until evenly mixed. Slice banana on top, cover and refrigerate overnight. In the morning, stir and drizzle with honey if desired.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Oat milk", quantity: "150ml" },
      { item: "Peanut butter", quantity: "1 tbsp" },
      { item: "Banana", quantity: "1" },
      { item: "Chia seeds", quantity: "1 tsp" },
      { item: "Honey", quantity: "1 tsp (optional)" },
    ],
  },
  "Mixed berry smoothie bowl with hemp seeds and granola": {
    instructions: "Blend frozen mixed berries, banana and a splash of milk until thick and smooth — keep it thicker than a drinkable smoothie. Pour into a bowl and top with granola, hemp seeds and extra fresh berries.",
    ingredients: [
      { item: "Frozen mixed berries", quantity: "150g" },
      { item: "Banana", quantity: "1/2, frozen" },
      { item: "Oat milk", quantity: "60ml" },
      { item: "Granola", quantity: "30g" },
      { item: "Hemp seeds", quantity: "1 tbsp" },
      { item: "Fresh berries", quantity: "handful" },
    ],
  },
  "Tofu scramble with peppers, onion and spinach": {
    instructions: "Drain and press firm tofu, then crumble it into small pieces. Heat olive oil in a pan over medium heat. Sauté diced onion and peppers for 3-4 minutes. Add crumbled tofu, turmeric, garlic powder and nutritional yeast, stirring well. Cook 5 minutes until heated through. Fold in spinach until wilted. Season to taste.",
    ingredients: [
      { item: "Firm tofu", quantity: "200g" },
      { item: "Red pepper, diced", quantity: "1/2" },
      { item: "Yellow pepper, diced", quantity: "1/2" },
      { item: "Onion, diced", quantity: "1/2" },
      { item: "Baby spinach", quantity: "60g" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Turmeric", quantity: "1/2 tsp" },
      { item: "Garlic powder", quantity: "1/2 tsp" },
      { item: "Nutritional yeast", quantity: "1 tbsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Fruit and nut muesli with oat milk": {
    instructions: "Combine muesli in a bowl with dried fruit and mixed nuts. Pour over cold oat milk and let it sit for 2-3 minutes to soften slightly. Top with fresh fruit if desired.",
    ingredients: [
      { item: "Muesli", quantity: "70g" },
      { item: "Oat milk", quantity: "200ml" },
      { item: "Dried apricots, chopped", quantity: "20g" },
      { item: "Raisins", quantity: "15g" },
      { item: "Mixed nuts (almonds, walnuts)", quantity: "20g" },
      { item: "Fresh fruit", quantity: "80g (optional)" },
    ],
  },
  // ── Missing Plant-Based Lunches & Dinners ──────────────────────────────────
  "Lentil and roasted vegetable bowl with tahini dressing": {
    instructions: "Preheat oven to 200°C. Toss chopped courgette, red pepper and sweet potato with olive oil and roast for 25 minutes. Meanwhile cook lentils according to packet instructions. Whisk tahini with lemon juice, garlic and a splash of water to make a dressing. Layer lentils and roasted veg in a bowl, drizzle with tahini dressing and garnish with fresh parsley.",
    ingredients: [
      { item: "Green or Puy lentils", quantity: "100g (dry)" },
      { item: "Sweet potato, cubed", quantity: "1 small" },
      { item: "Courgette, chopped", quantity: "1/2" },
      { item: "Red pepper, chopped", quantity: "1" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Tahini", quantity: "1 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Garlic clove, minced", quantity: "1" },
      { item: "Fresh parsley", quantity: "small handful" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Black bean and roasted pepper burrito bowl with guacamole": {
    instructions: "Cook rice according to packet instructions. Drain and rinse black beans. Roast sliced peppers in the oven at 200°C for 15 minutes. For guacamole, mash avocado with lime juice, diced red onion and salt. Assemble the bowl with rice, beans, roasted peppers, sweetcorn, guacamole and a squeeze of lime.",
    ingredients: [
      { item: "Brown rice", quantity: "80g (dry)" },
      { item: "Tin black beans, drained", quantity: "200g" },
      { item: "Red pepper, sliced", quantity: "1" },
      { item: "Sweetcorn", quantity: "80g" },
      { item: "Avocado", quantity: "1" },
      { item: "Lime", quantity: "1" },
      { item: "Red onion, diced", quantity: "2 tbsp" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Cumin", quantity: "1/2 tsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Chickpea and sweet potato bowl with spinach and lime": {
    instructions: "Preheat oven to 200°C. Toss cubed sweet potato with olive oil, cumin and smoked paprika, then roast for 25 minutes. Warm chickpeas in a pan with a pinch of salt. Serve sweet potato and chickpeas over fresh spinach, squeeze lime juice over the top and drizzle with olive oil.",
    ingredients: [
      { item: "Sweet potato, cubed", quantity: "1 medium" },
      { item: "Tin chickpeas, drained", quantity: "200g" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Lime", quantity: "1" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Cumin", quantity: "1/2 tsp" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Chickpea and spinach curry with basmati rice": {
    instructions: "Heat oil in a saucepan over medium heat. Sauté diced onion for 3 minutes, then add garlic, ginger and curry powder, stirring for 1 minute. Pour in chopped tomatoes and coconut milk, bring to a simmer. Add drained chickpeas and cook for 15 minutes. Stir in spinach until wilted. Serve over cooked basmati rice.",
    ingredients: [
      { item: "Tin chickpeas, drained", quantity: "400g" },
      { item: "Baby spinach", quantity: "100g" },
      { item: "Tin chopped tomatoes", quantity: "200g" },
      { item: "Coconut milk", quantity: "100ml" },
      { item: "Onion, diced", quantity: "1" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Fresh ginger, grated", quantity: "1 tsp" },
      { item: "Curry powder", quantity: "1 tbsp" },
      { item: "Basmati rice", quantity: "80g (dry)" },
      { item: "Vegetable oil", quantity: "1 tbsp" },
      { item: "Salt", quantity: "to taste" },
    ],
  },
  "Lentil dahl with brown rice and wilted spinach": {
    instructions: "Rinse red lentils and add to a saucepan with water, turmeric and salt. Bring to a boil, then simmer for 20 minutes until soft and soupy. In a separate pan, heat oil and fry cumin seeds, mustard seeds, garlic and chilli for 1 minute — pour this tempering over the dahl. Stir in spinach until wilted. Serve over cooked brown rice.",
    ingredients: [
      { item: "Red lentils", quantity: "120g (dry)" },
      { item: "Water", quantity: "500ml" },
      { item: "Turmeric", quantity: "1/2 tsp" },
      { item: "Cumin seeds", quantity: "1/2 tsp" },
      { item: "Mustard seeds", quantity: "1/4 tsp" },
      { item: "Garlic cloves, sliced", quantity: "2" },
      { item: "Dried chilli flakes", quantity: "1/4 tsp" },
      { item: "Baby spinach", quantity: "80g" },
      { item: "Brown rice", quantity: "80g (dry)" },
      { item: "Vegetable oil", quantity: "1 tbsp" },
      { item: "Salt", quantity: "to taste" },
    ],
  },
  "Tofu and vegetable stir-fry with brown rice": {
    instructions: "Press firm tofu and cut into cubes. Cook brown rice according to packet instructions. Heat sesame oil in a wok over high heat. Stir-fry tofu for 4-5 minutes until golden, then set aside. Add sliced vegetables and stir-fry for 3 minutes. Return tofu to the wok, pour in soy sauce and stir well. Serve over rice.",
    ingredients: [
      { item: "Firm tofu", quantity: "200g" },
      { item: "Brown rice", quantity: "80g (dry)" },
      { item: "Broccoli florets", quantity: "80g" },
      { item: "Red pepper, sliced", quantity: "1" },
      { item: "Carrot, julienned", quantity: "1" },
      { item: "Soy sauce", quantity: "2 tbsp" },
      { item: "Sesame oil", quantity: "1 tbsp" },
      { item: "Garlic clove, minced", quantity: "1" },
      { item: "Fresh ginger, grated", quantity: "1 tsp" },
    ],
  },
  "Roasted vegetable and quinoa bowl with tahini": {
    instructions: "Preheat oven to 200°C. Toss chopped courgette, aubergine, red onion and cherry tomatoes with olive oil and season. Roast for 25 minutes. Cook quinoa in water for 15 minutes until fluffy. Whisk tahini with lemon juice and a splash of water. Layer quinoa and roasted veg in a bowl, drizzle with tahini and scatter with fresh herbs.",
    ingredients: [
      { item: "Quinoa", quantity: "80g (dry)" },
      { item: "Courgette, chopped", quantity: "1/2" },
      { item: "Aubergine, cubed", quantity: "1/2" },
      { item: "Red onion, cut in wedges", quantity: "1/2" },
      { item: "Cherry tomatoes", quantity: "100g" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Tahini", quantity: "1 tbsp" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Fresh parsley or coriander", quantity: "small handful" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  // ── Missing Snacks ─────────────────────────────────────────────────────────
  "Apple slices with sunflower seed butter": {
    instructions: "Core and slice the apple. Spread sunflower seed butter on slices or serve in a small bowl for dipping.",
    ingredients: [
      { item: "Apple", quantity: "1 medium" },
      { item: "Sunflower seed butter", quantity: "1 tbsp" },
    ],
  },
  "Rice cakes with avocado and cherry tomatoes": {
    instructions: "Halve the cherry tomatoes. Mash avocado with a pinch of salt and a squeeze of lime. Spread avocado on rice cakes and top with cherry tomato halves. Finish with a pinch of chilli flakes if desired.",
    ingredients: [
      { item: "Rice cakes", quantity: "2" },
      { item: "Avocado", quantity: "1/2" },
      { item: "Cherry tomatoes", quantity: "6" },
      { item: "Lime juice", quantity: "1 tsp" },
      { item: "Salt", quantity: "pinch" },
      { item: "Chilli flakes", quantity: "pinch (optional)" },
    ],
  },
  "Roasted chickpeas with spices": {
    instructions: "Preheat oven to 200°C. Drain and pat chickpeas very dry with a tea towel. Toss with olive oil, smoked paprika, cumin and salt. Spread on a baking tray in a single layer and roast for 25-30 minutes, shaking halfway, until crunchy.",
    ingredients: [
      { item: "Tin chickpeas, drained", quantity: "200g" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Cumin", quantity: "1/2 tsp" },
      { item: "Salt", quantity: "1/4 tsp" },
    ],
  },
  // ── Missing Fancy Breakfasts ─────────────────────────────────────────────
  "Acai smoothie bowl with mixed berries, banana and coconut flakes": {
    instructions: "Blend frozen acai packet with frozen banana and a splash of milk until very thick. Pour into a bowl. Arrange mixed berries, coconut flakes and granola on top in rows.",
    ingredients: [
      { item: "Frozen acai packet", quantity: "100g" },
      { item: "Banana", quantity: "1, frozen" },
      { item: "Oat milk", quantity: "60ml" },
      { item: "Mixed berries", quantity: "80g" },
      { item: "Coconut flakes", quantity: "1 tbsp" },
      { item: "Granola", quantity: "25g" },
    ],
  },
  "Roasted tomato and lentil shakshuka with charred flatbread": {
    instructions: "Preheat oven to 200°C. Halve tomatoes and roast cut-side up for 15 minutes. In an oven-safe pan, sauté onion and garlic, add cumin and paprika, then stir in cooked lentils and the roasted tomatoes. Make small wells and crack eggs in if desired (or leave vegan). Bake for 10 minutes. Char flatbread over an open flame or in a dry pan. Serve together.",
    ingredients: [
      { item: "Vine tomatoes", quantity: "4" },
      { item: "Cooked Puy lentils", quantity: "100g" },
      { item: "Onion, diced", quantity: "1/2" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Cumin", quantity: "1 tsp" },
      { item: "Smoked paprika", quantity: "1 tsp" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Flatbread", quantity: "1" },
      { item: "Fresh coriander", quantity: "small handful" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Sweet potato and black bean breakfast hash with avocado": {
    instructions: "Dice sweet potato into small cubes. Heat oil in a pan over medium heat and cook sweet potato for 10 minutes, stirring occasionally, until golden and tender. Add drained black beans, cumin and smoked paprika, cook 3 more minutes. Serve topped with sliced avocado, a squeeze of lime and chilli flakes.",
    ingredients: [
      { item: "Sweet potato, diced", quantity: "1 medium" },
      { item: "Tin black beans, drained", quantity: "150g" },
      { item: "Avocado", quantity: "1/2" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Cumin", quantity: "1/2 tsp" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Lime", quantity: "1/2" },
      { item: "Chilli flakes", quantity: "pinch" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  // ── Missing Fancy Lunches & Dinners ──────────────────────────────────────
  "Moroccan roasted vegetable and chickpea bowl with chermoula": {
    instructions: "Preheat oven to 200°C. Toss cubed butternut squash, courgette and red onion with olive oil, cumin, cinnamon and salt, then roast for 25 minutes. For the chermoula, blend coriander, parsley, garlic, cumin, lemon juice and olive oil in a blender. Warm chickpeas in a pan. Layer roasted veg and chickpeas in a bowl, spoon over the chermoula and scatter with pomegranate seeds.",
    ingredients: [
      { item: "Butternut squash, cubed", quantity: "150g" },
      { item: "Courgette, chopped", quantity: "1/2" },
      { item: "Red onion, cut in wedges", quantity: "1/2" },
      { item: "Tin chickpeas, drained", quantity: "200g" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Ground cumin", quantity: "1 tsp" },
      { item: "Ground cinnamon", quantity: "1/4 tsp" },
      { item: "Fresh coriander", quantity: "large handful" },
      { item: "Fresh parsley", quantity: "large handful" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Lemon juice", quantity: "2 tbsp" },
      { item: "Pomegranate seeds", quantity: "2 tbsp" },
      { item: "Salt", quantity: "to taste" },
    ],
  },
  "Vietnamese-style tofu and glass noodle salad with lime dressing": {
    instructions: "Press tofu and slice into strips. Pan-fry in a little oil until golden on each side. Soak glass noodles in boiling water for 5 minutes, then drain and rinse under cold water. For the dressing, whisk lime juice, fish sauce (or soy sauce for vegan), sugar and chilli together. Toss noodles with shredded carrot, cucumber, herbs and tofu. Pour dressing over and mix well.",
    ingredients: [
      { item: "Firm tofu", quantity: "150g" },
      { item: "Glass noodles (vermicelli)", quantity: "60g (dry)" },
      { item: "Carrot, julienned", quantity: "1" },
      { item: "Cucumber, julienned", quantity: "1/2" },
      { item: "Fresh mint", quantity: "small handful" },
      { item: "Fresh coriander", quantity: "small handful" },
      { item: "Lime juice", quantity: "2 tbsp" },
      { item: "Soy sauce", quantity: "1 tbsp" },
      { item: "Caster sugar", quantity: "1 tsp" },
      { item: "Red chilli, sliced", quantity: "1/2" },
      { item: "Roasted peanuts, crushed", quantity: "1 tbsp" },
      { item: "Vegetable oil", quantity: "1 tsp" },
    ],
  },
  "Moroccan vegetable tagine with couscous, preserved lemon and harissa": {
    instructions: "Heat oil in a tagine or heavy-based pan. Sauté onion for 3 minutes, add garlic, ginger, cumin, cinnamon and coriander, stir for 1 minute. Add chopped carrots, sweet potato, courgette, tinned tomatoes and vegetable stock. Simmer for 25 minutes until tender. Stir in chickpeas and finely chopped preserved lemon for the last 5 minutes. Serve over couscous with a swirl of harissa and fresh coriander.",
    ingredients: [
      { item: "Carrots, chopped", quantity: "2" },
      { item: "Sweet potato, cubed", quantity: "1 small" },
      { item: "Courgette, chopped", quantity: "1" },
      { item: "Tin chopped tomatoes", quantity: "200g" },
      { item: "Vegetable stock", quantity: "200ml" },
      { item: "Tin chickpeas, drained", quantity: "150g" },
      { item: "Onion, diced", quantity: "1" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Fresh ginger, grated", quantity: "1 tsp" },
      { item: "Ground cumin", quantity: "1 tsp" },
      { item: "Ground cinnamon", quantity: "1/2 tsp" },
      { item: "Ground coriander", quantity: "1/2 tsp" },
      { item: "Preserved lemon, chopped", quantity: "1" },
      { item: "Harissa paste", quantity: "1 tsp" },
      { item: "Couscous", quantity: "80g (dry)" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Fresh coriander", quantity: "small handful" },
    ],
  },
  "Butternut squash and chickpea coconut curry with jasmine rice": {
    instructions: "Heat oil in a large saucepan. Sauté diced onion for 3 minutes, add garlic, ginger and curry paste, stirring for 1 minute. Add cubed butternut squash, pour in coconut milk and 100ml water. Simmer for 15 minutes, then add drained chickpeas and cook a further 10 minutes until squash is tender. Stir in spinach. Serve over jasmine rice with fresh coriander.",
    ingredients: [
      { item: "Butternut squash, cubed", quantity: "200g" },
      { item: "Tin chickpeas, drained", quantity: "200g" },
      { item: "Coconut milk", quantity: "200ml" },
      { item: "Onion, diced", quantity: "1" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Fresh ginger, grated", quantity: "1 tsp" },
      { item: "Thai curry paste", quantity: "1 tbsp" },
      { item: "Baby spinach", quantity: "60g" },
      { item: "Jasmine rice", quantity: "80g (dry)" },
      { item: "Vegetable oil", quantity: "1 tbsp" },
      { item: "Fresh coriander", quantity: "small handful" },
    ],
  },
  "Roasted aubergine with pomegranate, walnut sauce and lentil rice": {
    instructions: "Preheat oven to 200°C. Halve aubergine lengthways, score the flesh and drizzle with olive oil. Roast cut-side down for 30 minutes until soft and golden. Cook lentils and rice together (add lentils 10 minutes before rice). For walnut sauce, blend walnuts with garlic, lemon juice, olive oil and a splash of water until creamy. Serve aubergine on lentil rice, spoon over walnut sauce and scatter with pomegranate seeds and parsley.",
    ingredients: [
      { item: "Aubergine", quantity: "1 large" },
      { item: "Puy lentils", quantity: "60g (dry)" },
      { item: "Basmati rice", quantity: "60g (dry)" },
      { item: "Walnuts", quantity: "40g" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Pomegranate seeds", quantity: "3 tbsp" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Fresh parsley", quantity: "small handful" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  // ── Missing Fancy Snacks ─────────────────────────────────────────────────
  "Sliced avocado with lime, chilli flakes and sesame rice cakes": {
    instructions: "Slice avocado and fan out on sesame rice cakes. Squeeze lime juice over the top and sprinkle with chilli flakes and a pinch of flaky sea salt.",
    ingredients: [
      { item: "Avocado", quantity: "1/2" },
      { item: "Sesame rice cakes", quantity: "2" },
      { item: "Lime juice", quantity: "1 tsp" },
      { item: "Chilli flakes", quantity: "pinch" },
      { item: "Flaky sea salt", quantity: "pinch" },
    ],
  },
  "Spiced roasted chickpeas with pomegranate molasses": {
    instructions: "Preheat oven to 200°C. Drain and pat chickpeas very dry. Toss with olive oil, cumin, smoked paprika, cinnamon and salt. Roast for 25-30 minutes until crunchy, shaking halfway. Drizzle with pomegranate molasses while still warm.",
    ingredients: [
      { item: "Tin chickpeas, drained", quantity: "200g" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Ground cumin", quantity: "1/2 tsp" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Ground cinnamon", quantity: "1/4 tsp" },
      { item: "Pomegranate molasses", quantity: "1 tsp" },
      { item: "Salt", quantity: "1/4 tsp" },
    ],
  },
  "Coconut and passion fruit chia pudding with mango compote and lime": {
    instructions: "Mix chia seeds with coconut milk and a squeeze of lime. Stir well, cover and refrigerate for at least 4 hours or overnight. For the compote, gently simmer diced mango with a splash of water and a squeeze of lime for 5 minutes until soft. Spoon chia pudding into a glass, top with mango compote and scoop out passion fruit seeds over the top.",
    ingredients: [
      { item: "Chia seeds", quantity: "40g" },
      { item: "Coconut milk", quantity: "200ml" },
      { item: "Passion fruit", quantity: "1" },
      { item: "Mango, diced", quantity: "1/2" },
      { item: "Lime", quantity: "1" },
    ],
  },
  // ── Missing Gourmet Breakfasts (top tier) ────────────────────────────────────────────
  "Warm spiced oat porridge with caramelised apple, date syrup and toasted seeds": {
    instructions: "Cook oats in milk over medium heat for 5 minutes, stirring in a pinch of cinnamon and cardamom. Meanwhile, sauté sliced apple in a little coconut oil and a pinch of cinnamon until golden and caramelised. Toast pumpkin and sunflower seeds in a dry pan until fragrant. Serve porridge topped with caramelised apple, a drizzle of date syrup and toasted seeds.",
    ingredients: [
      { item: "Rolled oats", quantity: "60g" },
      { item: "Oat milk", quantity: "200ml" },
      { item: "Apple, sliced", quantity: "1" },
      { item: "Coconut oil", quantity: "1 tsp" },
      { item: "Ground cinnamon", quantity: "1/2 tsp" },
      { item: "Ground cardamom", quantity: "1/4 tsp" },
      { item: "Date syrup", quantity: "1 tbsp" },
      { item: "Pumpkin seeds", quantity: "1 tbsp" },
      { item: "Sunflower seeds", quantity: "1 tbsp" },
    ],
  },
  "Roasted cherry tomato and avocado bruschetta with microgreens and hemp oil": {
    instructions: "Preheat oven to 180°C. Halve cherry tomatoes, toss with olive oil and a pinch of salt, roast for 15 minutes until soft and blistered. Toast sourdough slices. Mash avocado with a squeeze of lemon and season. Spread avocado on toast, pile on roasted tomatoes, scatter with microgreens and finish with a drizzle of hemp oil.",
    ingredients: [
      { item: "Sourdough bread", quantity: "2 slices" },
      { item: "Cherry tomatoes", quantity: "120g" },
      { item: "Avocado", quantity: "1" },
      { item: "Microgreens", quantity: "small handful" },
      { item: "Hemp oil", quantity: "1 tsp" },
      { item: "Olive oil", quantity: "1 tsp" },
      { item: "Lemon juice", quantity: "1 tsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  // ── Missing Gourmet Lunches & Dinners (top tier) ─────────────────────────────────────
  "Heritage tomato salad with white bean puree, basil oil and crispy capers": {
    instructions: "For the white bean puree, blend drained cannellini beans with garlic, lemon juice and olive oil until smooth. For the basil oil, blend fresh basil with olive oil and strain through a sieve. Pat capers dry and shallow-fry in olive oil for 1-2 minutes until crispy. Slice heritage tomatoes and arrange on a plate. Smear white bean puree on the plate, layer tomatoes on top, drizzle with basil oil and scatter with crispy capers and flaky salt.",
    ingredients: [
      { item: "Heritage tomatoes, mixed", quantity: "300g" },
      { item: "Tin cannellini beans, drained", quantity: "200g" },
      { item: "Fresh basil", quantity: "large handful" },
      { item: "Capers", quantity: "2 tbsp" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Lemon juice", quantity: "1 tbsp" },
      { item: "Extra virgin olive oil", quantity: "4 tbsp" },
      { item: "Flaky sea salt", quantity: "pinch" },
    ],
  },
  "Roasted beetroot and Puy lentil salad with orange dressing and walnuts": {
    instructions: "Preheat oven to 200°C. Wrap beetroot in foil and roast for 45-50 minutes until tender. Cool slightly, peel and cut into wedges. Cook Puy lentils for 20 minutes until tender but not mushy. For the dressing, whisk orange juice with orange zest, Dijon mustard, sherry vinegar and olive oil. Toss lentils and beetroot with the dressing. Plate up, scatter with toasted walnuts, fresh dill and rocket.",
    ingredients: [
      { item: "Raw beetroot", quantity: "2 medium" },
      { item: "Puy lentils", quantity: "80g (dry)" },
      { item: "Orange", quantity: "1 (juice and zest)" },
      { item: "Walnuts, toasted", quantity: "30g" },
      { item: "Dijon mustard", quantity: "1 tsp" },
      { item: "Sherry vinegar", quantity: "1 tbsp" },
      { item: "Extra virgin olive oil", quantity: "2 tbsp" },
      { item: "Rocket", quantity: "handful" },
      { item: "Fresh dill", quantity: "small handful" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Miso-glazed aubergine with black sesame rice and pickled cucumber": {
    instructions: "Preheat oven to 200°C. Halve aubergine and score the flesh in a cross-hatch. Mix white miso, mirin, rice vinegar and a little sesame oil into a glaze. Spread over the cut side of the aubergine. Roast for 25 minutes until deeply caramelised. Cook rice and stir through black sesame seeds. For the pickle, thinly slice cucumber and toss with rice vinegar, sugar, a pinch of salt and sesame seeds. Serve aubergine on sesame rice with pickled cucumber alongside.",
    ingredients: [
      { item: "Aubergine", quantity: "1 large" },
      { item: "White miso paste", quantity: "2 tbsp" },
      { item: "Mirin", quantity: "1 tbsp" },
      { item: "Rice vinegar", quantity: "2 tbsp" },
      { item: "Sesame oil", quantity: "1 tsp" },
      { item: "Sushi rice or short-grain rice", quantity: "80g (dry)" },
      { item: "Black sesame seeds", quantity: "1 tbsp" },
      { item: "Cucumber", quantity: "1/2" },
      { item: "Caster sugar", quantity: "1 tsp" },
      { item: "Salt", quantity: "pinch" },
    ],
  },
  "Roasted celeriac with truffle oil, hazelnut crumb and lentil ragu": {
    instructions: "Preheat oven to 180°C. Peel celeriac and cut into thick steaks (about 3cm). Brush with olive oil, season and roast for 35-40 minutes until golden and tender. For the hazelnut crumb, pulse toasted hazelnuts with breadcrumbs and a pinch of salt. For the lentil ragu, sauté onion, carrot and celery, add garlic and tinned tomatoes, then stir in cooked Puy lentils and simmer for 15 minutes. Serve celeriac on the ragu, scatter with hazelnut crumb and finish with a drizzle of truffle oil.",
    ingredients: [
      { item: "Celeriac", quantity: "1/2 (about 300g)" },
      { item: "Puy lentils, cooked", quantity: "100g" },
      { item: "Tin chopped tomatoes", quantity: "200g" },
      { item: "Onion, diced", quantity: "1/2" },
      { item: "Carrot, diced", quantity: "1 small" },
      { item: "Celery stick, diced", quantity: "1" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Hazelnuts, toasted", quantity: "30g" },
      { item: "Breadcrumbs", quantity: "2 tbsp" },
      { item: "Truffle oil", quantity: "1 tsp" },
      { item: "Olive oil", quantity: "1 tbsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Charred cauliflower steak with romesco, beluga lentils and herb oil": {
    instructions: "Preheat oven to 200°C. Cut cauliflower into thick steaks through the stem. Brush with olive oil and season. Sear in a hot oven-safe pan for 3 minutes per side, then roast for 20 minutes. For the romesco, blend roasted red pepper, almonds, garlic, sherry vinegar, smoked paprika and olive oil until smooth. Cook beluga lentils for 20 minutes until tender. For herb oil, blend parsley, basil and olive oil, then strain. Plate lentils, top with cauliflower steak, spoon romesco alongside and drizzle with herb oil.",
    ingredients: [
      { item: "Cauliflower", quantity: "1 medium (cut steaks from centre)" },
      { item: "Beluga (black) lentils", quantity: "80g (dry)" },
      { item: "Roasted red pepper (jarred)", quantity: "1" },
      { item: "Almonds", quantity: "20g" },
      { item: "Garlic clove", quantity: "1" },
      { item: "Sherry vinegar", quantity: "1 tbsp" },
      { item: "Smoked paprika", quantity: "1/2 tsp" },
      { item: "Fresh parsley", quantity: "large handful" },
      { item: "Fresh basil", quantity: "small handful" },
      { item: "Extra virgin olive oil", quantity: "4 tbsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  "Wild mushroom and chestnut bourguignon with pommes purée and roasted roots": {
    instructions: "Heat oil in a heavy-based pan. Sauté sliced onion and garlic for 3 minutes. Add mixed wild mushrooms and cook for 5 minutes until golden. Stir in tomato paste, red wine (or vegetable stock), thyme, bay leaf and cooked chestnuts. Simmer for 20 minutes until rich and thick. For pommes purée, boil potatoes until tender, drain and mash with plant-based butter and warm oat milk until very smooth. Roast carrots and parsnips at 200°C for 25 minutes. Serve bourguignon over pommes purée with roasted roots on the side.",
    ingredients: [
      { item: "Mixed wild mushrooms", quantity: "200g" },
      { item: "Cooked chestnuts", quantity: "80g" },
      { item: "Onion, sliced", quantity: "1" },
      { item: "Garlic cloves, minced", quantity: "2" },
      { item: "Tomato paste", quantity: "1 tbsp" },
      { item: "Red wine or vegetable stock", quantity: "150ml" },
      { item: "Fresh thyme", quantity: "3 sprigs" },
      { item: "Bay leaf", quantity: "1" },
      { item: "Potatoes (Maris Piper or similar)", quantity: "300g" },
      { item: "Plant-based butter", quantity: "2 tbsp" },
      { item: "Oat milk", quantity: "50ml" },
      { item: "Carrots, halved lengthways", quantity: "2" },
      { item: "Parsnips, halved lengthways", quantity: "2" },
      { item: "Olive oil", quantity: "2 tbsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
  // ── Missing Gourmet Snacks (top tier) ────────────────────────────────────────────────
  "Chilled watermelon with fresh mint, lime zest and hemp seeds": {
    instructions: "Cut watermelon into elegant wedges or cubes and arrange on a plate. Tear fresh mint leaves over the top. Zest lime over the watermelon and squeeze a little juice. Scatter with hemp seeds and serve chilled.",
    ingredients: [
      { item: "Watermelon", quantity: "200g" },
      { item: "Fresh mint", quantity: "6 leaves" },
      { item: "Lime", quantity: "1 (zest and juice)" },
      { item: "Hemp seeds", quantity: "1 tbsp" },
    ],
  },
  "Roasted white asparagus with lemon oil and capers on pumpernickel": {
    instructions: "Preheat oven to 200°C. Peel white asparagus spears from just below the tip. Toss with olive oil and a pinch of salt, then roast on a baking tray for 12-15 minutes until tender with light colour. Whisk together lemon juice, lemon zest and olive oil for the lemon oil. Arrange asparagus on slices of pumpernickel bread, drizzle with lemon oil, scatter with capers and finish with a grind of black pepper.",
    ingredients: [
      { item: "White asparagus", quantity: "6 spears" },
      { item: "Pumpernickel bread", quantity: "2 slices" },
      { item: "Capers", quantity: "1 tbsp" },
      { item: "Lemon", quantity: "1 (juice and zest)" },
      { item: "Extra virgin olive oil", quantity: "2 tbsp" },
      { item: "Salt & pepper", quantity: "to taste" },
    ],
  },
};

